plugins {
    id "com.android.application"
    id "org.jetbrains.kotlin.android"
    id "com.google.devtools.ksp"
    id "org.jetbrains.kotlin.plugin.serialization"
    id "kotlin-parcelize"
}



def defaultPropertiesFile = rootProject.file("buildsystem/default.properties")
def defaultProperties = new Properties()
defaultProperties.load(new FileInputStream(defaultPropertiesFile))

def keystorePropertiesFile = rootProject.file("buildsystem/keystore.properties")
if (keystorePropertiesFile.exists()) {
    defaultProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    namespace 'com.carlos.grabredenvelope'
    compileSdk 35
    defaultConfig {
        applicationId "com.carlos.gbd"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "2"

        ndk {
            //选择要添加的对应 cpu 类型的 .so 库。
            abiFilters 'armeabi-v7a', 'x86', 'arm64-v8a'
            // 还可以添加 'armeabi', 'arm64-v8a', 'x86_64', 'mips', 'mips64'
        }

        resConfigs 'zh'
        multiDexEnabled true
    }

    sourceSets {
        main.java.srcDirs = ["src/main/java"]
    }


    signingConfigs {
        release {
            keyAlias defaultProperties['keyAlias']
            keyPassword defaultProperties['keyPassword']
            storeFile file(defaultProperties['storeFile'])
            storePassword defaultProperties['storePassword']
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildFeatures {
        buildConfig true
        viewBinding true
    }

    bundle {
        language {//OPPO 有台机子多语言不生效，暂时屏蔽语言的拆包
            enableSplit = false
        }
    }

    //修改APK名字
    android.applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "GrabRedEnvelope${versionName}.apk"
        }
    }


}




dependencies {
//    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation libs.bundles.lifecycle

    implementation libs.kotlinx.serialization.json
    implementation libs.kotlin.immutable.collections
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.swiperefreshlayout

    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.gson

    implementation libs.bundles.room
    ksp libs.androidx.room.compiler


    //bug收集
    implementation "com.tencent.bugly:crashreport:4.1.9.3"

    implementation 'com.blankj:utilcodex:1.30.6'


    // 基础依赖包，必须要依赖
    implementation 'com.geyifeng.immersionbar:immersionbar:3.2.2'
    // kotlin扩展（可选）
    implementation 'com.geyifeng.immersionbar:immersionbar-ktx:3.2.2'

    implementation project(':cutils')

    implementation 'androidx.multidex:multidex:2.0.1'

//    implementation("com.squareup.okhttp3:okhttp:4.12.0")

}

